print("Welcome!")
print("\nSorted Marks Program")
marks1 = int(input("\nEnter the marks of 1st Student : "))
marks2 = int(input("Enter the marks of 2nd Student : "))
marks3 = int(input("Enter the marks of 3rd Student : "))
marks4 = int(input("Enter the marks of 4th Student : "))
marks5 = int(input("Enter the marks of 5th Student : "))
marksorted = [marks1, marks2, marks3, marks4, marks5]
marksorted.sort()
print("\nSorted Marks : ")
print(marksorted)